name: CI

on:
  push:
    branches:
      - main  # ここで指定したブランチにプッシュされたときにパイプラインが動作します

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 使用する Node.js のバージョンを指定

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build  # ビルドステップを追加

      - name: Install Firebase CLI  # Firebase CLI をインストールするステップを追加
        run: npm install -g firebase-tools

      - name: Set up Firebase authentication  # Firebase 認証の設定
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/service-account.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json

      # - name: Check GOOGLE_APPLICATION_CREDENTIALS  # デバッグ情報の追加
      #   run: cat $HOME/service-account.json

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          # GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        run: firebase deploy --only hosting   # 自動デプロイステップを追加



  # deploy:
  #   name: deploy
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Setup Node.js and cache
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "npm"
  #     - name: Install firebase-tools
  #       run: npm install --save-dev firebase-tools
  #     - name: Decode Firebase service account key
  #       run: |
  #         echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
  #         echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV
  #     - name: change space
  #       run: ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
  #     - name: Deploy to Firebase Hosting
  #       run: |
  #         ./node_modules/.bin/firebase deploy
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #         FIREBASE_CLI_EXPERIMENTS: webframeworks
  #     - name: delete GOOGLE_APPLICATION_CREDENTIALS
  #       run: rm $GOOGLE_APPLICATION_CREDENTIALS
  #       if: ${{ always() }}
